In [1]:
import spotipy
from spotipy.oauth2 import SpotifyOAuth
import os
import sys
import pandas as pd
import numpy as np
import requests
from spotify_dl import spotify_dl
from pathlib import Path
import time
import os
from dotenv import load_dotenv  # changed magic command to explicit load
import librosa
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.metrics import pairwise
from sklearn.model_selection import train_test_split
from typing import List
from flask import Flask, redirect, request
import random
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Flatten
from tensorflow.keras.applications import ResNet50V2
from tensorflow.keras.callbacks import EarlyStopping
from skimage.transform import resize


pd.set_option("display.max_rows", None)  # pandas dataframe formatting options
pd.set_option("display.max_columns", None)


custom_env_path = "../../../brainstation_capstone_cfg.env"  # environment variables file

In [2]:
# Spotify Developer Credentials
load_dotenv(dotenv_path=custom_env_path)
CLIENT_ID = os.environ.get("SPOTIPY_CLIENT_ID")
# client ID from app
CLIENT_SECRET = os.environ.get("SPOTIPY_CLIENT_SECRET")
# client secret from app
REDIRECT_URI = os.environ.get("REDIRECT_URI")
# redirect URI - the URI used here matches the one used within the app
SCOPE = "{} {}".format(os.environ.get("SCOPE_PUBLIC"), os.environ.get("SCOPE_PRIVATE"))
# formatted the scope this way to allow for custom configurations in the future
USERNAME = os.environ.get("SPOTIFY_USERNAME")
# Spotify username

In [11]:
kaggle_df = pd.read_csv('../../data/SpotifyFeatures.csv')

In [4]:
normal_df = pd.read_parquet(
    "../../data/vectorized_mp3s/pairwise_complete_parquets/20230901_complete_pairwise_data.parquet"
)
normal_df.shape

(11578, 498)

In [5]:
cnn_df = pd.read_parquet(
    "../../data/vectorized_mp3s/cnn_complete_parquets/20230901_complete_cnn_data.parquet"
)
cnn_df.shape

(11578, 1000)

In [6]:
normal_similarity = pairwise.cosine_similarity(normal_df, dense_output=True)
normal_similarity

array([[1.        , 0.97973231, 0.99154322, ..., 0.98798471, 0.9864652 ,
        0.96577147],
       [0.97973231, 1.        , 0.98947364, ..., 0.98547464, 0.99003342,
        0.98766516],
       [0.99154322, 0.98947364, 1.        , ..., 0.99357991, 0.99600081,
        0.98262735],
       ...,
       [0.98798471, 0.98547464, 0.99357991, ..., 1.        , 0.99601647,
        0.98547392],
       [0.9864652 , 0.99003342, 0.99600081, ..., 0.99601647, 1.        ,
        0.9892527 ],
       [0.96577147, 0.98766516, 0.98262735, ..., 0.98547392, 0.9892527 ,
        1.        ]])

In [7]:
normal_similarity_sorted = np.argsort(normal_similarity)[:, ::-1]

In [9]:
vec = list(normal_similarity_sorted[7085, 0:11])
normal_similarity[7085, vec]  # similarity for first match

array([1.        , 0.99678356, 0.99594064, 0.99573878, 0.99568158,
       0.99548641, 0.99543346, 0.99539609, 0.9953861 , 0.99531449,
       0.9949721 ])

In [ ]:
normal_recommendation_df = kaggle_df.copy(deep=True)
normal_recommendation_df["track_id"] = normal_recommendation_df["track_id"].astype(
    "category"
)
normal_recommendation_df[
    "track_id"
] = normal_recommendation_df.track_id.cat.set_categories(normal_recommendations[3])
# normal_recommendation_df[
#     "track_id"
# ] = normal_recommendation_df.track_id.cat.set_categories(normal_recommendations[3])

normal_track_recommendations = normal_recommendation_df.copy(deep=True).sort_values(
    ["track_id"]
)  # sorts heirarchy
# track_recommendations.head()
normal_track_recommendations = normal_track_recommendations.drop_duplicates(
    subset="track_id"
)
normal_track_recommendations.head(11)

In [12]:
unique_track_ids = pd.read_parquet('../../data/20230903_unique_track_ids_for_training.parquet')

In [13]:
track_ids = unique_track_ids.track_ids.unique().tolist()

In [14]:
training_mp3s_df = kaggle_df.loc[(kaggle_df.track_id.str.strip().isin(track_ids))].drop(columns = 'genre').drop_duplicates(subset='track_id')
# training_mp3s_df.to_parquet('../../data/20230905_training_mp3s.parquet')

In [17]:
training_mp3s_df.loc[training_mp3s_df.artist_name.str.lower().str.strip().str.contains('jessie ware')]

artist_name   track_name                track_id  popularity  \
86463  Jessie Ware  Til The End  3184gD1FUstNCMVZMtuQ9W          40   

       acousticness  danceability  duration_ms  energy  instrumentalness key  \
86463         0.703         0.695       182827   0.398             0.239  F#   

       liveness  loudness   mode  speechiness    tempo time_signature  valence  
86463    0.0783   -12.791  Minor       0.0652  145.958          4-Apr    0.578

#### CNN Similarity

In [62]:
cnn_similarity = pairwise.cosine_similarity(cnn_df, dense_output=True)
cnn_similarity

array([[0.9999999 , 0.96258837, 0.99975014, ..., 0.9996804 , 0.7478662 ,
        0.8212553 ],
       [0.96258837, 0.9999997 , 0.96280265, ..., 0.9655044 , 0.7904676 ,
        0.9046931 ],
       [0.99975014, 0.96280265, 0.99999994, ..., 0.9994428 , 0.7471412 ,
        0.81841034],
       ...,
       [0.9996804 , 0.9655044 , 0.9994428 , ..., 1.        , 0.75507843,
        0.83261484],
       [0.7478662 , 0.7904676 , 0.7471412 , ..., 0.75507843, 1.0000006 ,
        0.71857   ],
       [0.8212553 , 0.9046931 , 0.81841034, ..., 0.83261484, 0.71857   ,
        0.99999964]], dtype=float32)

In [63]:
cnn_similarity_sorted = np.argsort(cnn_similarity)[:, ::-1]

#### Check Normal Recommendations

In [66]:
normal_recommendation_df = kaggle_df.copy(deep=True)
dissimilar_recommendation_df = kaggle_df.copy(deep=True)
normal_recommendation_df["track_id"] = normal_recommendation_df["track_id"].astype(
    "category"
)
normal_recommendation_df[
    "track_id"
] = normal_recommendation_df.track_id.cat.set_categories(normal_recommendations[3])
# normal_recommendation_df[
#     "track_id"
# ] = normal_recommendation_df.track_id.cat.set_categories(normal_recommendations[3])

normal_track_recommendations = normal_recommendation_df.copy(deep=True).sort_values(
    ["track_id"]
)  # sorts heirarchy
# track_recommendations.head()
normal_track_recommendations = normal_track_recommendations.drop_duplicates(
    subset="track_id"
)
normal_track_recommendations.head(11)

genre             artist_name  \
180270        Jazz   Green Assassin Dollar   
180055        Jazz                BluntOne   
146179        Jazz                BluntOne   
61009          R&B              The Marías   
145515        Jazz                BluntOne   
145808        Jazz                 tusken.   
25703   Electronic                   Ozoyo   
145939        Jazz                 FloFilz   
44120         Folk  Vancouver Sleep Clinic   
199078  Soundtrack           Ramin Djawadi   
177513        Jazz              Kevoe West   

                                               track_name  \
180270                                              Aware   
180055                                         Recogneyes   
146179                                   Ghost Train Haze   
61009                                            Loverboy   
145515                                         Loved Ones   
145808                                             mocean   
25703                         Where to Go (feat. Wun Two)   
145939                                          Gelbstich   
44120                                           Ayahuasca   
199078  To Vaes Dothrak - From The "Game Of Thrones" S...   
177513                                           Playdout   

                      track_id  popularity  acousticness  danceability  \
180270  2QbR9yeeX7XHznRZwsyh3F          34        0.8420         0.720   
180055  6zP7r08qkY9GIWJ7TxVV6E          35        0.7820         0.607   
146179  56ir9LGNYpV3O4U5ShDvn9          50        0.5490         0.566   
61009   3XCpEFU4uXsBq5WmVQQKC9          48        0.8080         0.651   
145515  43iOWRh6448rFtwBX6CAfZ          57        0.1630         0.811   
145808  0KFF0INOF9PT3GYWbVjfI4          56        0.7380         0.759   
25703   0fDnP59qSG3dlo1j1z1fHl          34        0.1780         0.469   
145939  7niUZWARcEMEntcEOeiTH4          55        0.5430         0.740   
44120   6oVm5ocTB8B0rjO5dZk8Px          51        0.7340         0.463   
199078  6hJA1KQ8AK2r1mazUOQWGM          41        0.7970         0.465   
177513  4pNc7TWXJb9OUbI1cd0kGM          41        0.0562         0.799   

        duration_ms  energy  instrumentalness key  liveness  loudness   mode  \
180270        73500   0.268             0.958   A    0.1420   -12.323  Minor   
180055       100043   0.354             0.855   B    0.1150    -8.413  Minor   
146179       113468   0.125             0.543   B    0.1250    -9.770  Minor   
61009         73236   0.152             0.422   G    0.1170   -18.704  Minor   
145515        99765   0.181             0.880   E    0.0861   -11.996  Minor   
145808       149318   0.225             0.843   B    0.1500   -13.165  Minor   
25703        106667   0.372             0.909  A#    0.1480   -12.275  Major   
145939       117774   0.265             0.973  C#    0.1150   -11.693  Major   
44120        508602   0.228             0.110   E    0.0691   -15.717  Minor   
199078        88867   0.254             0.897  G#    0.0946   -24.967  Major   
177513       100465   0.357             0.628  A#    0.2010   -14.053  Minor   

        speechiness    tempo time_signature  valence  
180270       0.1020   80.132          4-Apr   0.4040  
180055       0.1060   78.832          4-Apr   0.8310  
146179       0.1360  128.428          4-May   0.5240  
61009        0.0832  131.088          4-Apr   0.0746  
145515       0.4460   38.498          4-Apr   0.4690  
145808       0.1290   88.022          4-Apr   0.3850  
25703        0.3240  121.355          4-Mar   0.6670  
145939       0.0461   82.040          4-Apr   0.4120  
44120        0.0338  148.003          4-Apr   0.0528  
199078       0.0351  160.108          4-Mar   0.1150  
177513       0.1410   85.987          4-Apr   0.8720

In [67]:
# kaggle_df.loc[kaggle_df.track_id.isin(dissimilar_recommendations[3])].sort_values(by ='track_id', key = dissimilar_recommendations[3])
kaggle_df.set_index("track_id").loc[dissimilar_recommendations[3]].reset_index(
    inplace=False
).drop_duplicates(subset="track_id")

track_id        genre             artist_name  \
0   2QbR9yeeX7XHznRZwsyh3F         Jazz   Green Assassin Dollar   
1   7wobmC9Xz4stYN1ZVLWgi5         Soul             Alicia Keys   
2   4oarDDCWsSnX2WOIRKuQo1        Blues            Jimi Hendrix   
3   11SY8jJkg1CtUgHx37qUlm        Dance                  Miguel   
5   2s9M78CDrQDjB2D827XXr4  Alternative    The Naked And Famous   
9   5oICBRkaGVtLTkkKeXuSKF      Hip-Hop                   Jeezy   
11  0vybyrCk6ANFFmDTBWq74f  Alternative  Francis and the Lights   
12  2C6FKqjI3CT4Q0YjOlAQAl        World        Michael W. Smith   
13  6cZ8T2c95NfRTrGEXqThIq      Country           Willie Nelson   
14  2SNtwYtk9a4THKlERP0bMN  Alternative  Francis and the Lights   
17  7bX0AR2q50IfDu0TnmTdwP        Blues              Juicy Lucy   

                  track_name  popularity  acousticness  danceability  \
0                      Aware          34       0.84200         0.720   
1   Elaine Brown (Interlude)          35       0.95500         0.673   
2          Up From The Skies          41       0.60300         0.659   
3                Shockandawe          44       0.35200         0.766   
5                     Higher          48       0.00649         0.463   
9                Snow Season          49       0.09510         0.711   
11                    Cruise          38       0.10900         0.858   
12                  Thy Word          26       0.19200         0.405   
13         Django and Jimmie          40       0.55600         0.547   
14                   Morning          45       0.96900         0.657   
17          Who Do You Love?          31       0.00419         0.456   

    duration_ms  energy  instrumentalness key  liveness  loudness   mode  \
0         73500   0.268          0.958000   A    0.1420   -12.323  Minor   
1         50187   0.364          0.000000   A    0.2800   -12.828  Minor   
2        177867   0.635          0.021400  A#    0.1720   -10.569  Minor   
3        150730   0.902          0.000000   C    0.4970    -7.067  Major   
5        230747   0.766          0.000017  F#    0.5810    -5.383  Major   
9        204907   0.569          0.000000  G#    0.0999    -7.832  Major   
11       216161   0.332          0.065300   C    0.1160   -12.177  Major   
12       210373   0.412          0.756000   G    0.3000   -11.837  Major   
13       173453   0.407          0.000110   D    0.3480   -12.214  Major   
14        97675   0.250          0.018600  D#    0.1080   -10.423  Major   
17       180147   0.923          0.005160   A    0.2750    -7.496  Major   

    speechiness    tempo time_signature  valence  
0        0.1020   80.132          4-Apr    0.404  
1        0.9010   89.549          4-Jan    0.705  
2        0.2020  144.965          4-Apr    0.413  
3        0.1040  109.032          4-Apr    0.470  
5        0.0511  184.075          4-Apr    0.173  
9        0.0560  101.993          4-Apr    0.155  
11       0.0638  140.010          4-Apr    0.480  
12       0.0278  147.964          4-Apr    0.132  
13       0.0381  129.030          4-Mar    0.329  
14       0.0457   88.325          4-Apr    0.467  
17       0.1120  115.526          4-Apr    0.342

In [68]:
vec = list(normal_similarity_sorted[7085, -10:])
normal_similarity[7085, vec]  # similarity for first match

array([0.92794647, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [69]:
vec = list(normal_similarity_sorted[7085, 0:11])
normal_similarity[7085, vec]  # similarity for first match

array([1.        , 0.99678356, 0.99594064, 0.99573878, 0.99568158,
       0.99548641, 0.99543346, 0.99539609, 0.9953861 , 0.99531449,
       0.9949721 ])

In [70]:
np.mean(normal_similarity[7085, vec])

0.996012108539831

#### Check CNN Recommendations

In [71]:
cnn_recommendation_df = kaggle_df.copy(deep=True)
cnn_recommendation_df["track_id"] = cnn_recommendation_df["track_id"].astype("category")
cnn_recommendation_df["track_id"] = cnn_recommendation_df.track_id.cat.set_categories(
    cnn_recommendations[3]
)

In [72]:
cnn_track_recommendations = cnn_recommendation_df.copy(deep=True).sort_values(
    ["track_id"]
)  # sorts heirarchy
# track_recommendations.head()
cnn_track_recommendations = cnn_track_recommendations.drop_duplicates(subset="track_id")
cnn_track_recommendations.head(11)

genre               artist_name  \
180270        Jazz     Green Assassin Dollar   
147873        Jazz                      Mujo   
205057  Soundtrack         Marc Streitenfeld   
180425        Jazz                  BluntOne   
89353      Hip-Hop              A$AP Twelvyy   
147190        Jazz                Lemongrass   
210093       World                 Brian Eno   
199145  Soundtrack              Trent Reznor   
220597       World               Entheogenic   
127720   Classical            Akira Kosemura   
133576      Reggae  Bob Marley & The Wailers   

                                               track_name  \
180270                                              Aware   
147873                           Mirror (feat. Made in M)   
205057                                              Alpha   
180425                                          Sahasrara   
89353                                            Strapped   
147190                                        Sunset Glow   
210093         Thursday Afternoon - 2005 Digital Remaster   
199145                                        Sugar Storm   
220597                                              Torah   
127720                                         Grow Apart   
133576  War / No More Trouble - Live at the Stanley Th...   

                      track_id  popularity  acousticness  danceability  \
180270  2QbR9yeeX7XHznRZwsyh3F          34        0.8420        0.7200   
147873  6qFTyyX88gmlPokNdf8h2z          44        0.5520        0.7240   
205057  3tDfBzg1VZBL3MkEm6bbIp          30        0.9690        0.1020   
180425  68huIHGDHk1kBNM0ofSUUk          36        0.4060        0.8370   
89353   3U0xbYGTtYZAUv3lEwPebJ          55        0.4590        0.7240   
147190  37R2gf2GpGrKuQffKCTzbF          49        0.7600        0.4990   
210093  4t3Yh6tKkxXrc458pNI7zZ          38        0.9760        0.0918   
199145  4ktkHx7JtPUk2D6ma7tUQ7          38        0.9680        0.2360   
220597  1IkxzTnEP1p0IYWU21qC1y          28        0.0504        0.5460   
127720  3IQOIjxF1OfeIZ9Hg5UBtN          34        0.9610        0.4470   
133576  6x8IAEZoyLlNLK76u2Dc6l          29        0.2160        0.4870   

        duration_ms  energy  instrumentalness key  liveness  loudness   mode  \
180270        73500  0.2680          0.958000   A    0.1420   -12.323  Minor   
147873        94250  0.0526          0.953000  C#    0.1080   -15.380  Major   
205057       136027  0.1500          0.950000   C    0.0688   -22.262  Major   
180425        96152  0.3760          0.864000   D    0.1100    -8.305  Major   
89353        197867  0.5340          0.000058  G#    0.1520    -8.631  Minor   
147190       279219  0.3750          0.896000   A    0.6480   -10.372  Minor   
210093      3650688  0.0569          0.884000   C    0.0842   -31.808  Major   
199145       173613  0.0347          0.885000   A    0.0836   -22.849  Minor   
220597       451373  0.6060          0.721000   B    0.6540   -11.574  Minor   
127720        80880  0.2720          0.860000   F    0.1230   -21.012  Major   
133576       363893  0.7530          0.000001  F#    0.9540    -7.581  Minor   

        speechiness    tempo time_signature  valence  
180270       0.1020   80.132          4-Apr   0.4040  
147873       0.1520   81.605          4-Apr   0.7140  
205057       0.0349   72.551          4-Apr   0.0620  
180425       0.1350   82.910          4-Apr   0.5120  
89353        0.3530   87.987          4-Apr   0.1120  
147190       0.0281   80.095          4-Apr   0.0772  
210093       0.0358   81.945          4-Mar   0.0527  
199145       0.0335   71.506          4-May   0.0732  
220597       0.0300  133.947          4-Apr   0.0972  
127720       0.0438   75.391          4-Mar   0.1200  
133576       0.2890  158.439          4-Apr   0.5970

In [73]:
vec = list(cnn_similarity_sorted[7085, 0:11])
cnn_similarity[7085, vec]  # similarity for first match

array([1.        , 0.9990518 , 0.98749137, 0.9763511 , 0.9221045 ,
       0.9151948 , 0.89406407, 0.8691619 , 0.8667479 , 0.83266383,
       0.80967844], dtype=float32)

In [74]:
np.mean(cnn_similarity[7085, vec])

0.9156826

In [75]:
np.corrcoef(
    normal_similarity_sorted.flatten(), cnn_similarity_sorted.flatten()
)  # uncorrelated in terms of rank?

array([[ 1.00000000e+00, -7.51160957e-05],
       [-7.51160957e-05,  1.00000000e+00]])

In [76]:
normal_df.head()

0         1         2         3         4  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.446197  0.432998  0.526217  0.585114  0.453538   
1Bk00Y8bvqKHzUTDfEH2RH  0.533089  0.496410  0.529498  0.539816  0.602047   
7x8MCsillTMQGAStE4dmW8  0.375435  0.506404  0.403135  0.446927  0.366386   
11uz9XML4cezgIT4LO9Zq7  0.561327  0.488023  0.637125  0.450111  0.357839   
63eqAbSLuqUQiT8wDOMWLF  0.484749  0.380538  0.420095  0.410116  0.317550   

                               5         6         7         8         9  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.393470  0.381640  0.472515  0.441829  0.436484   
1Bk00Y8bvqKHzUTDfEH2RH  0.531111  0.583465  0.500657  0.547362  0.595350   
7x8MCsillTMQGAStE4dmW8  0.480915  0.499774  0.416219  0.522652  0.362109   
11uz9XML4cezgIT4LO9Zq7  0.402176  0.474751  0.366066  0.320569  0.442026   
63eqAbSLuqUQiT8wDOMWLF  0.372825  0.370876  0.447128  0.441618  0.361918   

                              10        11        12        13        14  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.582131  0.429712  0.000000  0.000000  0.000000   
1Bk00Y8bvqKHzUTDfEH2RH  0.530005  0.601916  0.013502  0.008879  0.025781   
7x8MCsillTMQGAStE4dmW8  0.391583  0.318410  0.003151  0.004168  0.007821   
11uz9XML4cezgIT4LO9Zq7  0.595346  0.789375  0.008911  0.009713  0.010991   
63eqAbSLuqUQiT8wDOMWLF  0.385281  0.408907  0.003759  0.002013  0.004323   

                              15        16        17        18        19  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000000  0.000000  0.000000  0.000000  0.000000   
1Bk00Y8bvqKHzUTDfEH2RH  0.017854  0.016353  0.032633  0.033187  0.020770   
7x8MCsillTMQGAStE4dmW8  0.000650  0.000268  0.000343  0.000210  0.001007   
11uz9XML4cezgIT4LO9Zq7  0.007270  0.004633  0.004885  0.008912  0.004726   
63eqAbSLuqUQiT8wDOMWLF  0.007078  0.005656  0.004919  0.002898  0.005598   

                              20        21        22        23   24   25   26  \
track_id                                                                        
6DQzmTJnaZw4A9IynCGfrM  0.000000  0.000000  0.000000  0.000000  1.0  1.0  1.0   
1Bk00Y8bvqKHzUTDfEH2RH  0.020561  0.019715  0.021397  0.017325  1.0  1.0  1.0   
7x8MCsillTMQGAStE4dmW8  0.003574  0.000611  0.000178  0.003449  1.0  1.0  1.0   
11uz9XML4cezgIT4LO9Zq7  0.005685  0.006983  0.005052  0.003019  1.0  1.0  1.0   
63eqAbSLuqUQiT8wDOMWLF  0.001808  0.006693  0.011461  0.002518  1.0  1.0  1.0   

                         27   28   29   30   31   32   33   34   35  \
track_id                                                              
6DQzmTJnaZw4A9IynCGfrM  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
1Bk00Y8bvqKHzUTDfEH2RH  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
7x8MCsillTMQGAStE4dmW8  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
11uz9XML4cezgIT4LO9Zq7  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
63eqAbSLuqUQiT8wDOMWLF  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   

                               36         37         38         39         40  \
track_id                                                                        
6DQzmTJnaZw4A9IynCGfrM -28.965864 -21.389360 -19.317324 -21.354130 -21.516270   
1Bk00Y8bvqKHzUTDfEH2RH -26.442589 -20.350389 -16.736059 -16.068079 -15.998079   
7x8MCsillTMQGAStE4dmW8 -27.700293 -25.555010 -27.493561 -30.544888 -27.802584   
11uz9XML4cezgIT4LO9Zq7 -35.881554 -31.713604 -28.821924 -30.741623 -28.591974   
63eqAbSLuqUQiT8wDOMWLF -39.543922 -33.366390 -29.568184 -32.599480 -33.892006   

                               41         42         43         44         45  \
track_id                                                                        
6DQzmTJnaZw4A9IynCGfrM -23.200346 -24.177885 -25.294035 -24.751333 -24.149071   
1Bk00Y8bvqKHzUTDfEH2RH

In [77]:
cnn_df.head()

0         1         2         3         4  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000033  0.000073  0.000034  0.000046  0.000038   
1Bk00Y8bvqKHzUTDfEH2RH  0.000092  0.000472  0.000130  0.000257  0.000349   
7x8MCsillTMQGAStE4dmW8  0.000007  0.000020  0.000009  0.000016  0.000019   
11uz9XML4cezgIT4LO9Zq7  0.000425  0.000524  0.000323  0.000799  0.000594   
63eqAbSLuqUQiT8wDOMWLF  0.000155  0.000305  0.000123  0.000304  0.000209   

                               5         6         7         8         9  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000055  0.000064  0.000059  0.000017  0.000049   
1Bk00Y8bvqKHzUTDfEH2RH  0.000602  0.000645  0.000100  0.000097  0.000260   
7x8MCsillTMQGAStE4dmW8  0.000028  0.000056  0.000012  0.000015  0.000035   
11uz9XML4cezgIT4LO9Zq7  0.002035  0.000453  0.000129  0.000225  0.000444   
63eqAbSLuqUQiT8wDOMWLF  0.001102  0.000286  0.000102  0.000056  0.000110   

                              10        11        12        13        14  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000018  0.000029  0.000026  0.000024  0.000016   
1Bk00Y8bvqKHzUTDfEH2RH  0.000065  0.000098  0.000097  0.000090  0.000050   
7x8MCsillTMQGAStE4dmW8  0.000013  0.000010  0.000012  0.000012  0.000008   
11uz9XML4cezgIT4LO9Zq7  0.000265  0.000142  0.000089  0.000118  0.000056   
63eqAbSLuqUQiT8wDOMWLF  0.000083  0.000070  0.000073  0.000093  0.000031   

                              15        16        17        18        19  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000047  0.000059  0.000027  0.000013  0.000028   
1Bk00Y8bvqKHzUTDfEH2RH  0.000166  0.000128  0.000106  0.000106  0.000081   
7x8MCsillTMQGAStE4dmW8  0.000022  0.000021  0.000015  0.000008  0.000011   
11uz9XML4cezgIT4LO9Zq7  0.000599  0.000420  0.000161  0.000085  0.000139   
63eqAbSLuqUQiT8wDOMWLF  0.000120  0.000108  0.000079  0.000044  0.000088   

                              20        21        22        23        24  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000032  0.000047  0.000053  0.000039  0.000015   
1Bk00Y8bvqKHzUTDfEH2RH  0.000174  0.000129  0.000132  0.000217  0.000113   
7x8MCsillTMQGAStE4dmW8  0.000015  0.000014  0.000016  0.000020  0.000015   
11uz9XML4cezgIT4LO9Zq7  0.000211  0.000297  0.000281  0.000161  0.000312   
63eqAbSLuqUQiT8wDOMWLF  0.000097  0.000112  0.000095  0.000115  0.000060   

                              25        26        27        28        29  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000043  0.000041  0.000036  0.000027  0.000084   
1Bk00Y8bvqKHzUTDfEH2RH  0.000103  0.000198  0.000095  0.000103  0.000404   
7x8MCsillTMQGAStE4dmW8  0.000013  0.000018  0.000012  0.000012  0.000019   
11uz9XML4cezgIT4LO9Zq7  0.000323  0.000564  0.000181  0.000226  0.000874   
63eqAbSLuqUQiT8wDOMWLF  0.000117  0.000312  0.000109  0.000081  0.000857   

                              30        31        32        33        34  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000063  0.000050  0.000039  0.000075  0.000028   
1Bk00Y8bvqKHzUTDfEH2RH  0.000260  0.000141  0.000156  0.000320  0.000117   
7x8MCsillTMQGAStE4dmW8  0.000043  0.000027  0.000018  0.000022  0.000011   
11uz9XML4cezgIT4LO9Zq7  0.000252  0.000222  0.000282  0.002537  0.000337   
63eqAbSLuqUQiT8wDOMWLF  0.000160  0.000142  0.000242  0.000310  0.000163   

                              35        36        37        38        39  \
track_id                                                                   
6DQzmTJnaZw4A9IynCGfrM  0.000126  0.000147  0.000026  0.000031  0.000015   
1Bk00Y8bvqKHzUTDfEH2RH  0.000551  0.000520  0.000103  0.000213  0.000076

In [91]:
# Initialize SpotifyOAuth
sp_oauth = SpotifyOAuth(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    redirect_uri=REDIRECT_URI,
    scope=SCOPE,
    cache_path="../.cache",
    show_dialog=False,
)


def main(normal_recommendations: List, cnn_recommendations: List):
    # Get cached token or start authorization process
    access_token_info = sp_oauth.get_cached_token()
    if access_token_info:
        access_token = access_token_info["access_token"]
    else:
        print("Authorization required. Visit the following URL to authorize:")
        auth_url = sp_oauth.get_authorize_url()
        print(auth_url)
        return

    # Initialize spotipy with access token
    sp = spotipy.Spotify(auth=access_token)

    # Replace 'Your Username' with your Spotify username
    username = USERNAME
    for track_recommendation in normal_recommendations:
        playlist_name = (
            f"Pairwise Recommendation Playlist for Track {track_recommendation[0]}"
        )
        playlist_description = f"These are the top 10 pairwise matches for track {track_recommendation[0]} by cosine similarity in descending order."

        try:
            # Create a blank playlist
            playlist = sp.user_playlist_create(
                user=username,
                name=playlist_name,
                description=playlist_description,
                public=False,
            )
            print(f"Pairwise Playlist '{playlist_name}' was created")
        except spotipy.SpotifyException as e:
            print(f"An error occurred: {e}")

        # List of track IDs (URIs) to add to the playlist
        prefix = "spotify:track:"
        track_uris = list(prefix + x for x in track_recommendation)

        # track_ids = [
        #     'spotify:track:track_id_1',
        #     'spotify:track:track_id_2',
        #     # Add more track IDs here
        # ]

        # Add tracks to the playlist
        sp.user_playlist_add_tracks(
            user=username, playlist_id=playlist["id"], tracks=track_uris
        )
    for track_recommendation in cnn_recommendations:
        playlist_name = (
            f"CNN Recommendation Playlist for Track {track_recommendation[0]}"
        )
        playlist_description = f"These are the top 10 CNN matches for track {track_recommendation[0]} by cosine similarity in descending order."

        try:
            # Create a blank playlist
            playlist = sp.user_playlist_create(
                user=username,
                name=playlist_name,
                description=playlist_description,
                public=False,
            )
            print(f"CNN Playlist '{playlist_name}' was created")
        except spotipy.SpotifyException as e:
            print(f"An error occurred: {e}")

        # List of track IDs (URIs) to add to the playlist
        prefix = "spotify:track:"
        track_uris = list(prefix + x for x in track_recommendation)

        # track_ids = [
        #     'spotify:track:track_id_1',
        #     'spotify:track:track_id_2',
        #     # Add more track IDs here
        # ]

        # Add tracks to the playlist
        sp.user_playlist_add_tracks(
            user=username, playlist_id=playlist["id"], tracks=track_uris
        )


if __name__ == "__main__":
    main(normal_recommendations, cnn_recommendations)

Pairwise Playlist 'Pairwise Recommendation Playlist for Track 0OBwxFLu6Yj61s2OagYbgY' was created
CNN Playlist 'CNN Recommendation Playlist for Track 0OBwxFLu6Yj61s2OagYbgY' was created


In [93]:
test = normal_df.copy(deep=True).reset_index()
# test.head()
test.loc[test.track_id == "2Ud3deeqLAG988pfW0Kwcl"]  # track of interest

track_id         0         1         2         3  \
2584  2Ud3deeqLAG988pfW0Kwcl  0.243606  0.279533  0.221751  0.377492   

             4         5         6         7         8         9        10  \
2584  0.821773  0.322402  0.251372  0.292876  0.504456  0.726703  0.466291   

            11        12        13        14        15        16        17  \
2584  0.405033  0.012553  0.011789  0.012059  0.034747  0.049094  0.030988   

            18        19        20       21        22        23   24   25  \
2584  0.006959  0.005367  0.014339  0.04432  0.028594  0.027951  1.0  1.0   

       26   27   28   29   30   31   32   33   34   35        36         37  \
2584  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0 -38.94215 -33.411198   

             38        39         40         41         42         43  \
2584 -27.197319 -25.98834 -28.496126 -26.440634 -23.633427 -27.841377   

             44         45         46         47         48         49  \
2584 -31.502941 -28.530811 -29.500467 -35.594536 -29.059072 -24.223267   

             50         51         52         53         54         55  \
2584 -30.281403 -40.678936 -40.305477 -40.635609 -40.719402 -28.809755   

             56         57         58         59         60         61  \
2584 -25.825352 -31.108908 -34.871922 -37.133602 -42.198986 -42.865707   

             62         63         64         65        66         67  \
2584 -37.164165 -33.464024 -38.311775 -43.096985 -37.78894 -39.333748   

             68         69        70         71         72         73  \
2584 -44.299236 -42.941689 -42.95945 -45.042435 -44.411121 -44.810745   

             74         75         76         77         78         79  \
2584 -35.489132 -26.436434 -31.048096 -44.406891 -43.199005 -39.363285   

             80         81         82         83         84        85  \
2584 -36.872723 -40.464821 -39.217854 -39.462654 -33.148026 -37.68293   

             86         87         88         89         90         91  \
2584 -46.391037 -34.810688 -31.784929 -42.347023 -41.847343 -35.020813   

             92         93         94         95         96        97  \
2584 -37.123158 -42.661163 -47.764488 -48.864964 -42.116486 -38.49205   

             98         99        100        101        102       103  \
2584 -48.110703 -48.385899 -49.011467 -46.204517 -44.528805 -49.68465   

            104        105      106        107        108      109        110  \
2584 -47.741024 -48.759232 -48.8069 -51.744366 -55.321804 -50.0173 -47.933483   

            111        112        113        114        115       116  \
2584 -53.692467 -52.980701 -51.925297 -54.313755 -54.153793 -54.84063   

            117       118        119        120        121        122  \
2584 -54.732479 -55.70475 -54.633133 -56.871857 -57.116005 -56.215881   

            123        124        125        126        127        128  \
2584 -58.624977 -56.333954 -56.680477 -58.806572 -58.434856 -60.391422   

            129        130        131        132        133        134  \
2584 -59.402897 -59.515972 -59.416206 -59.520176 -59.883743 -60.007778   

           135        136        137        138       139        140  \
2584 -61.62899 -62.821804 -63.292274 -63.218468 -62.27903 -61.968254   

            141        142        143       144        145        146  \
2584 -62.476582 -62.814266 -63.528908 -63.56155 -64.316391 -65.687294   

            147        148        149        150        151        152  \
2584 -67.870659 -70.390434 -73.051033 -75.888878 -79.017975 -79.996567   

          153        154        155        156       157        158  \
2584 -79.9972 -79.996246 -79.997475 -79.997879 -79.99839 -79.998421   

            159        160        161        162        163   164   165  \
2584 -79.998444 -79.998466 -79.998482 -79.998497 -79.998512 -80.0 -80.0   

            166       167        168        169        170        171  \
2584 -70.005447 -65.79068 -63.435143 -64.251625 -68.94264

In [94]:
np.random.seed(123)
normal_rows = [2584]
normal_recommendations = []
dissimilar_recommendations = []
for normal_row in normal_rows:
    vec = list(normal_similarity_sorted[normal_row, 0:11])
    anti_vec = list(normal_similarity_sorted[normal_row, -10:][::-1])
    # selects vector from array
    recommendation_vec = list(normal_df.iloc[vec, :].index)
    dissimilar_vec = [recommendation_vec[0]] + list(normal_df.iloc[anti_vec, :].index)
    normal_recommendations.append(recommendation_vec)
    dissimilar_recommendations.append(dissimilar_vec)

In [95]:
normal_recommendations

[['2Ud3deeqLAG988pfW0Kwcl',
  '7LJzs1Kr8kW3d6cFTCueNV',
  '5WDlNHQW1LmcQIA15oGjiW',
  '49ihmTS9428yqABTmqQ16Y',
  '1Ly6ZKvHfosVneVTEIvMbR',
  '47W6YR93MPCGLEUReLMyDm',
  '47wtXjG0Sk6DI6cjkRBcEg',
  '3UiNahTo7xKY5qFY6Fgr0b',
  '3LWpOcr8kYmsHvqZsTLxna',
  '30vXWNZxO57z3kljfOFy02',
  '4bUnIY5kXGJKLaIO7rr3N9']]

In [98]:
np.random.seed(123)
cnn_rows = [2584]
cnn_recommendations = []
for cnn_row in cnn_rows:
    vec = list(cnn_similarity_sorted[cnn_row, 0:11])  # selects vector from array
    recommendation_vec = list(cnn_df.iloc[vec, :].index)
    cnn_recommendations.append(recommendation_vec)

In [99]:
main(normal_recommendations, cnn_recommendations)

Pairwise Playlist 'Pairwise Recommendation Playlist for Track 2Ud3deeqLAG988pfW0Kwcl' was created
CNN Playlist 'CNN Recommendation Playlist for Track 2Ud3deeqLAG988pfW0Kwcl' was created


In [236]:
vec = list(normal_similarity_sorted[10623, 0:11])
normal_similarity[10623, vec]

array([1.        , 0.99600455, 0.99565072, 0.99565072, 0.99547629,
       0.99539676, 0.99498592, 0.99497752, 0.99448599, 0.99441314,
       0.99431788])

In [237]:
vec = list(cnn_similarity_sorted[10623, 0:11])
cnn_similarity[10623, vec]

array([0.9999998 , 0.999767  , 0.99970776, 0.9995883 , 0.9995862 ,
       0.99951774, 0.99945426, 0.99944305, 0.99937904, 0.9992693 ,
       0.9991413 ], dtype=float32)

In [32]:
test2 = normal_df.copy(deep=True).reset_index()
# test.head()
test2.loc[test2.track_id == "7wobmC9Xz4stYN1ZVLWgi5"]

track_id    0    1    2    3    4    5    6    7    8  \
5446  7wobmC9Xz4stYN1ZVLWgi5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

        9   10   11   12   13   14   15   16   17   18   19   20   21   22  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       23   24   25   26   27   28   29   30   31   32   33   34   35   36  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       37   38   39   40   41   42   43   44   45   46   47   48   49   50  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       51   52   53   54   55   56   57   58   59   60   61   62   63   64  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       65   66   67   68   69   70   71   72   73   74   75   76   77   78  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       79   80   81   82   83   84   85   86   87   88   89   90   91   92  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       93   94   95   96   97   98   99  100  101  102  103  104  105  106  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      107  108  109  110  111  112  113  114  115  116  117  118  119  120  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      121  122  123  124  125  126  127  128  129  130  131  132  133  134  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      135  136  137  138  139  140  141  142  143  144  145  146  147  148  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      149  150  151  152  153  154  155  156  157  158  159  160  161  162  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      163  164  165  166  167  168  169  170  171  172  173  174  175  176  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      177  178  179  180  181  182  183  184  185  186  187  188  189  190  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      191  192  193  194  195  196  197  198  199  200  201  202  203  204  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      205  206  207  208  209  210  211  212  213  214  215  216  217  218  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      219  220  221  222  223  224  225  226  227  228  229  230  231  232  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      233  234  235  236  237  238  239  240  241  242  243  244  245  246  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      247  248  249  250  251  252  253  254  255  256  257  258  259  260  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      261  262  263  264  265  266  267  268  269  270  271  272  273  274  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      275  276  277  278  279  280  281  282  283  284  285  286  287  288  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      289  290  291  292  293  294  295  296  297  298  299  300  301  302  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      303  304  305  306  307  308  309  310  311  312  313  314  315  316  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      317  318  319  320  321  322  323  324  325  326  327  328  329  330  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      331  332  333  334  335  336  337  338  339  340  341  342  343  344  \
5446  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      345  346  347  348  349  350  351  352  353  354  355  356  357  358  \
5446  0.0  0.0  0.0

In [34]:
kaggle_df.loc[kaggle_df.track_id.str.strip() == "2SNtwYtk9a4THKlERP0bMN"]

genre             artist_name track_name  \
9450        Alternative  Francis and the Lights    Morning   
60708               R&B  Francis and the Lights    Morning   
99684  Children’s Music  Francis and the Lights    Morning   

                     track_id  popularity  acousticness  danceability  \
9450   2SNtwYtk9a4THKlERP0bMN          45         0.969         0.657   
60708  2SNtwYtk9a4THKlERP0bMN          49         0.969         0.657   
99684  2SNtwYtk9a4THKlERP0bMN          49         0.969         0.657   

       duration_ms  energy  instrumentalness key  liveness  loudness   mode  \
9450         97675    0.25            0.0186  D#     0.108   -10.423  Major   
60708        97675    0.25            0.0186  D#     0.108   -10.423  Major   
99684        97675    0.25            0.0186  D#     0.108   -10.423  Major   

       speechiness   tempo time_signature  valence  
9450        0.0457  88.325          4-Apr    0.467  
60708       0.0457  88.325          4-Apr    0.467  
99684       0.0457  88.325          4-Apr    0.467